package Loggia::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Loggia::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dbname=loggia',
        user => 'loggia',
        password => '10gg14',
    }
);

=head1 NAME

Loggia::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Loggia>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Loggia::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

Alan Haggai Alavi

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
